# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "mysql2-cs-bind"
gem "rack-flash3"
gem "unicorn"
gem "foreman"
gem "rack-lineprof"
gem "rack-mini-profiler"
gem "flamegraph"
gem "stackprof"
gem "redis"
gem "hiredis"
